STATE_PAYMENT_PATTERNS_BASE = [
    ('AL', '(AB) (CD) E F G H'),
    ('AK', 'A B C D E'),
    ('AZ', 'A B C D'),
    ('CA', '(AB) C D (EF) G H I J'),
    ('CO', '(AB) C D E F'),
    ('CT', 'A'),
    ('DE', 'A'),
    ('DC', 'A B C D E F G'),
    ('FL', '(AB) C (DEF) (GHI) (JKLMN) O'),
    ('HI', 'A B C D'),
    ('ID', 'A B C D E F G H I'),
    ('IL', ''),
    ('IN', 'A'),
    ('IA', 'A B (CD) E (FG) H %IJIIIJJJ%'),
    ('KY', '(AB) C'),
    ('LA', 'A'),
    ('ME', 'A B C D E F'),
    ('MD', '(ABCD)'),
    ('MA', '(ABC) (DEF) (GHI) (JK) L'),
    ('MI', 'A B C D E F G H'),
    ('MN', 'A B C D'),
    ('MO', 'A B C D'),
    ('MT', 'A B C D E'),
    ('NE', 'A B C D E F (GH) I'),
    ('NV', '(AB) (CD) E'),
    ('NH', 'A B (CDE)'),
    ('NJ', 'A B (CD) E F'),
    ('NM', 'A'),
    ('NY', 'A B (CD) (EF) (GH) I J'),
    ('NC', 'A B (CD)'),
    ('ND', ''),
    ('OH', 'A B C'),
    ('OK', 'A'),
    ('OR', 'A B C D E (FG) (HI) (JK)'),
    ('PA', 'A %BBCCBBCC% D E'),
    ('RI', 'A B C'),
    ('SC', 'A'),
    ('SD', 'A (BC)'),
    ('UT', 'A'),
    ('VT', 'A B C D E F G H'),
    ('VA', '(AB) (CD)'),
    ('WA', '(AB) (CD) E F (GH) I J'),
    ('WI', 'A B C D E F G H I'),
    ('WY', 'A B')
]